# frozen_string_literal: true

# Copyright 2023 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

require_relative 'config/environment'
require 'sinatra/activerecord/rake'

Bundler.require

ActiveRecord::Base.establish_connection(
  adapter: 'postgresql',
  database: 'activerecord',
  host: ENV['PGHOST'] || 'localhost',
  port: ENV['PGPORT'] || '5432',
  pool: 5,
  # Advisory locks are not supported by PGAdapter
  advisory_locks: false,
  # These settings ensure that migrations and schema inspections work.
  variables: {
    "spanner.ddl_transaction_mode": "AutocommitExplicitTransaction",
    "spanner.emulate_pg_class_tables": "true"
  },
)

desc 'Runs a simple ActiveRecord tutorial for Google Cloud Spanner PostgreSQL.'
task :run do
  begin
    sh 'rake db:seed'
    sh 'ruby application.rb'
  end
end
