/* Generated By:JavaCC: Do not edit this line. CopyTreeConstants.java Version 7.0.11 */
package com.google.cloud.spanner.pgadapter.parsers.copy;

public interface CopyTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTCOPYSTATEMENT = 2;
  public int JJTQUALIFIEDNAME = 3;
  public int JJTCOLUMNLIST = 4;
  public int JJTCOLUMNELEMENT = 5;
  public int JJTCOPYFROM = 6;
  public int JJTFILENAME = 7;
  public int JJTCOPYOPTIONS = 8;
  public int JJTCOPYOPTIONLIST = 9;
  public int JJTCOPYOPTIONELEMENT = 10;
  public int JJTID = 11;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "CopyStatement",
    "QualifiedName",
    "ColumnList",
    "ColumnElement",
    "CopyFrom",
    "Filename",
    "CopyOptions",
    "CopyOptionList",
    "CopyOptionElement",
    "ID",
  };
}
/* JavaCC - OriginalChecksum=bc0b779bf9f53da6579402764aa248b7 (do not edit this line) */
