

# Recommended Hikari configuration.

# Set the maximum pool size to the maximum number of concurrent transactions that one instance
# of your application should be able to execute.
spring.datasource.hikari.maximum-pool-size=10
# Set the minimum number of idle connections to the expected number of concurrent transactions.
# The recommended setting is to keep this equal to the maximum pool size.
spring.datasource.hikari.minimum-idle=5
# The amount of time that a connection must not have been used for it to be considered idle.
# This setting only has an effect if min-idle is smaller than max-pool-size (which is not recommended).
spring.datasource.hikari.idle-timeout=10000
# The maximum time that a JDBC connection is kept in the pool before being replaced with a new
# connection.
spring.datasource.hikari.max-lifetime=10000
# The timeout that should be used when checking whether a connection is still valid.
spring.datasource.hikari.validation-timeout=5000
# The leak detection threshold is the maximum number of milliseconds that a JDBC connection can be
# out of the pool before Hikari logs a warning that it **might** have been leaked. Setting this
# value to a value close to the connection timeout helps in detecting potential connection leaks,
# which again could lead to connection timeouts. It should be larger than the statement timeout.
spring.datasource.hikari.leak-detection-threshold=2000
# Set the maximum time that a thread should wait to get a connection from the pool.
# A thread will be blocked if all the connections in the pool are in use.
# It is recommended to add a statement timeout to the JDBC connection URL that is smaller than this
# connection timeout. This will cause slow statements to fail and return connections to the pool.
# Otherwise, slow statements might keep connections out of the pool for a long time without returning
# any errors, while new transactions cannot be started, as there are no connections in the pool.
spring.datasource.hikari.connection-timeout=10000

# These additional JDBC options are added to the JDBC connection URL.
# The statement_timeout option sets a default timeout for all statements to 25 seconds. This is
# slightly less than the connection timeout.
#
# The 'options=-c%20spanner.ddl_transaction_mode=AutocommitExplicitTransaction' addition at the end
# of the connection URL instructs PGAdapter to commit the current transaction if it encounters a DDL
# statement in a transaction. All following DDL statements will then be executed as a DDL batch.
# This is needed to support Liquibase, as Liquibase will use DDL transactions when it is connected
# to PostgreSQL.
spanner.jdbc_options=options=-c%20spanner.ddl_transaction_mode=AutocommitExplicitTransaction

# This is the connection string to PGAdapter running in-process.
# We use a fully qualified database name, so we can start PGAdapter without a fixed project or instance.
spring.datasource.url=jdbc:postgresql://localhost:${pgadapter.port}/projects%2F${spanner.project}%2Finstances%2F${spanner.instance}%2Fdatabases%2F${spanner.database}?${spanner.jdbc_options}&connectTimeout=1000&socketTimeout=1000

# The example uses the standard PostgreSQL Hibernate dialect.
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# This sample by default runs on the Spanner emulator. Disable this to run on a real Spanner
# instance.
spanner.use_emulator=false

# Defining these properties here makes it a bit easier to build the connection string.
# Change these to match your Cloud Spanner PostgreSQL-dialect database.
spanner.project=my-project
spanner.instance=my-instance
spanner.database=my-database
# This setting ensures that PGAdapter automatically commits the current transaction if it encounters
# a DDL statement in a read/write transaction, and then executes the DDL statements as a single DDL
# batch.
spanner.ddl_transaction_mode=options=-c%20spanner.ddl_transaction_mode=AutocommitExplicitTransaction%20-c%20statement_timeout=2000

# The TCP port where PGAdapter is listening for incoming connection requests.
# This sample automatically starts PGAdapter in-process and assigns it a random port.
# The port number in this file is therefore by default overridden by the application.
pgadapter.port=5432

# This sample uses Liquibase for schema management. It is highly recommended to use a higher level
# schema management tool like Liquibase, instead of letting Hibernate generate the schema.
# Instead, just let Hibernate validate the schema that is created by Liquibase (or similar).
# This also allows you to use Spanner-specific features like interleaved tables.
spring.jpa.hibernate.ddl-auto=none

# Set this property to true to see all SQL statements that are being executed.
spring.jpa.show-sql=false

# Enable JDBC batching. This will improve the performance of the application, as most inserts and
# updates will be sent in batches instead of individual statements to Cloud Spanner.
spring.jpa.properties.hibernate.jdbc.batch_size=50
# order_inserts=true will order the inserts by entity type. This enables Hibernate to batch more
# statements.
spring.jpa.properties.hibernate.order_inserts=true

# This prevents a JPA error warning to be logged. (Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented).
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
