// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.cloud.spanner.pgadapter.sample.model;

import com.google.cloud.spanner.hibernate.annotations.PooledBitReversedSequenceGenerator;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.util.List;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * This entity uses a bit-reversed sequence to generate a primary key. The strategy it uses is
 * compatible with Hibernate batching.
 *
 * <p>The ID generator it uses is defined in this dependency:
 *
 * <pre>{@code
 * <dependency>
 *   <groupId>com.google.cloud</groupId>
 *   <artifactId>google-cloud-spanner-hibernate-tools</artifactId>
 * </dependency>
 * }</pre>
 *
 * <p>The table and sequence definition that is used for this entity can be found in the file
 * resources/db.changelog-v1.1.sql.
 */
@Table(name = "ticket_sales")
@Entity
public class TicketSale extends AbstractBaseEntity {
  @Id
  // This entity uses a bit-reversed sequence to generate primary key values. Note that it uses an
  // explicit sequence and not for example a serial, bigserial or identity column. It is recommended
  // not to use serial or identity for primary key generation with Hibernate, as it reduces the
  // options that Hibernate has to batch and optimize insert statements. When using a sequence,
  // Hibernate can pre-fetch a batch of primary key values and include these in the insert
  // statement. This again allows Hibernate to send those insert statements as one batch to the
  // database and reduce the overall number of roundtrips.
  @PooledBitReversedSequenceGenerator(
      // Use a separate sequence name for each entity.
      // See resources/db.changelog-v1.1.sql file for the sequence definition in the database.
      sequenceName = "ticket_sale_seq",
      // The poolSize is not actually set on the sequence that is created, but is used to
      // generate a SELECT query that fetches this number of identifiers at once.
      poolSize = 200,
      startWithCounter = 50000,
      // Add any range that should be excluded by the generator if your table already
      // contains existing values that have been generated by other generators.
      excludeRange = "[1,1000]")
  public Long id;

  @ManyToOne(optional = false, fetch = FetchType.LAZY)
  private Concert concert;

  private String customerName;

  private BigDecimal price;

  /** This column is mapped to a text[] column in the database. */
  @JdbcTypeCode(SqlTypes.ARRAY)
  private List<String> seats;

  public TicketSale() {}

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Concert getConcert() {
    return concert;
  }

  public void setConcert(Concert concert) {
    this.concert = concert;
  }

  public String getCustomerName() {
    return customerName;
  }

  public void setCustomerName(String customerName) {
    this.customerName = customerName;
  }

  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public List<String> getSeats() {
    return seats;
  }

  public void setSeats(List<String> seats) {
    this.seats = seats;
  }
}
