/* Generated By:JJTree: Do not edit this line. ASTCopyOptionList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.google.cloud.spanner.pgadapter.parsers.copy;

public
class ASTCopyOptionList extends SimpleNode {
  public ASTCopyOptionList(int id) {
    super(id);
  }

  public ASTCopyOptionList(Copy p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CopyVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8098a34852741307325964e12f63cf1a (do not edit this line) */
