/* Generated By:JJTree: Do not edit this line. ASTNamespace.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.google.cloud.spanner.pgadapter.parsers.copy;

public
class ASTNamespace extends SimpleNode {
  public ASTNamespace(int id) {
    super(id);
  }

  public ASTNamespace(Copy p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CopyVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ec6f85d57bb58dd60dbf14b0ef234d00 (do not edit this line) */
