/* Generated By:JJTree: Do not edit this line. ASTUnicode.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.google.cloud.spanner.pgadapter.parsers.copy;

public class ASTUnicode extends SimpleNode {
  public ASTUnicode(int id) {
    super(id);
  }

  public ASTUnicode(Copy p, int id) {
    super(p, id);
  }

  /** Accept the visitor. * */
  public Object jjtAccept(CopyVisitor visitor, Object data) {

    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c2ecaa98495cdbf67b6054766f928566 (do not edit this line) */
