/* Generated By:JavaCC: Do not edit this line. CopyTreeConstants.java Version 7.0.11 */
package com.google.cloud.spanner.pgadapter.parsers.copy;

public interface CopyTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTCOPYSTATEMENT = 2;
  public int JJTQUALIFIEDNAME = 3;
  public int JJTCOLUMNLIST = 4;
  public int JJTCOLUMNELEMENT = 5;
  public int JJTCOPYDIRECTION = 6;
  public int JJTFILENAME = 7;
  public int JJTCOPYOPTIONS = 8;
  public int JJTCOPYOPTIONLIST = 9;
  public int JJTCOPYOPTIONELEMENT = 10;
  public int JJTFORMATTYPE = 11;
  public int JJTID = 12;
  public int JJTSINGLECHAR = 13;
  public int JJTBOOLEAN = 14;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "CopyStatement",
    "QualifiedName",
    "ColumnList",
    "ColumnElement",
    "CopyDirection",
    "Filename",
    "CopyOptions",
    "CopyOptionList",
    "CopyOptionElement",
    "FormatType",
    "ID",
    "SingleChar",
    "Boolean",
  };
}
/* JavaCC - OriginalChecksum=900593ffbcdb66e5db2a975119b80880 (do not edit this line) */
