/* Generated By:JavaCC: Do not edit this line. CopyTreeConstants.java Version 7.0.11 */
package com.google.cloud.spanner.pgadapter.parsers.copy;

public interface CopyTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTCOPYSTATEMENT = 2;
  public int JJTQUALIFIEDNAME = 3;
  public int JJTNAMESPACE = 4;
  public int JJTCOLUMNLIST = 5;
  public int JJTCOLUMNELEMENT = 6;
  public int JJTCOPYDIRECTION = 7;
  public int JJTFILENAME = 8;
  public int JJTCOPYOPTIONS = 9;
  public int JJTCOPYOPTIONLIST = 10;
  public int JJTCOPYOPTIONELEMENT = 11;
  public int JJTFORMATTYPE = 12;
  public int JJTID = 13;
  public int JJTSINGLECHAR = 14;
  public int JJTBOOLEAN = 15;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "CopyStatement",
    "QualifiedName",
    "Namespace",
    "ColumnList",
    "ColumnElement",
    "CopyDirection",
    "Filename",
    "CopyOptions",
    "CopyOptionList",
    "CopyOptionElement",
    "FormatType",
    "ID",
    "SingleChar",
    "Boolean",
  };
}
/* JavaCC - OriginalChecksum=fc32b0be9096c1ad19c44efb2a419f4c (do not edit this line) */
