/* Generated By:JavaCC: Do not edit this line. CopyDefaultVisitor.java Version 7.0.11 */
package com.google.cloud.spanner.pgadapter.parsers.copy;

public class CopyDefaultVisitor implements CopyVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCopyStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTQualifiedName node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNamespace node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTColumnList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTColumnElement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCopyDirection node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFilename node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCopyOptions node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCopyOptionList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCopyOptionElement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFormatType node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTID node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSingleChar node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBoolean node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=5a4f53d1bba42fe3e2c197a73700ded1 (do not edit this line) */
