on:
  push:
    branches:
      - postgresql-dialect
  pull_request:
name: go-sample-test
permissions:
  contents: read
env:
  GOOGLE_CLOUD_PROJECT: "span-cloud-testing"
  GOOGLE_CLOUD_INSTANCE: "pgadapter-testing"
  GOOGLE_CLOUD_DATABASE: "testdb_integration"
  GOOGLE_CLOUD_ENDPOINT: "spanner.googleapis.com"
jobs:
  check-env:
    outputs:
      has-key: ${{ steps.project-id.outputs.defined }}
    runs-on: ubuntu-latest
    steps:
      - id: project-id
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        if: "${{ env.GCP_PROJECT_ID != '' }}"
        run: echo "defined=true" >> "$GITHUB_OUTPUT"
  sample-test:
    needs: [check-env]
    if: needs.check-env.outputs.has-key == 'true'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: zulu
          java-version: 11
      - run: java -version
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.26.x'
      - name: Auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          credentials_json: ${{ secrets.JSON_SERVICE_ACCOUNT_CREDENTIALS }}
      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - run: go version
      - name: Run Go wrapper tests
        working-directory: ./wrappers/golang
        run: go test
