on:
  pull_request:
  schedule:
    # Run at 04:52UTC every day. This run will use preprod-spanner.sandbox.googleapis.com
    - cron: '52 4 * * *'
    # Run at 03:14UTC every day. This run will use staging-wrenchworks.sandbox.googleapis.com
    - cron: '14 3 * * *'
  workflow_dispatch:
    inputs:
      endpoint:
        description: "The Spanner endpoint to use for the tests"
        required: true
        type: choice
        options:
          - spanner.googleapis.com
          - staging-wrenchworks.sandbox.googleapis.com
          - preprod-spanner.sandbox.googleapis.com
name: integration
permissions:
  contents: read
env:
  GOOGLE_CLOUD_PROJECT: "span-cloud-testing"
  GOOGLE_CLOUD_INSTANCE: "pgadapter-testing"
  GOOGLE_CLOUD_DATABASE: "testdb_integration"
  GOOGLE_CLOUD_ENDPOINT: "spanner.googleapis.com"
  PG_ADAPTER_DROP_STALE_DATABASES: true
jobs:
  check-env:
    outputs:
      has-key: ${{ steps.project-id.outputs.defined }}
    runs-on: ubuntu-latest
    steps:
      - id: project-id
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        if: "${{ env.GCP_PROJECT_ID != '' }}"
        run: echo "defined=true" >> "$GITHUB_OUTPUT"
  integration-test:
    needs: [check-env]
    if: needs.check-env.outputs.has-key == 'true'
    permissions:
      contents: read
      issues: write
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # Add a PostgreSQL Docker container
    services:
      # Container label
      postgres:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        ports:
          - 5432:5432
        volumes:
          - /pg:/var/run/postgresql
          - /tmp:/tmp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - id: set-manual-endpoint
        if: "${{ inputs.endpoint }}"
        env:
          ENDPOINT: ${{ inputs.endpoint }}
        run: |
          echo "GOOGLE_CLOUD_ENDPOINT=$ENDPOINT" >> $GITHUB_ENV
      - id: set-preprod-scheduled-endpoint
        if: github.event.schedule=='52 4 * * *'
        run: |
          echo "GOOGLE_CLOUD_ENDPOINT=preprod-spanner.sandbox.googleapis.com" >> $GITHUB_ENV
      - id: set-staging-scheduled-endpoint
        if: github.event.schedule=='14 3 * * *'
        run: |
          echo "GOOGLE_CLOUD_ENDPOINT=staging-wrenchworks.sandbox.googleapis.com" >> $GITHUB_ENV
      # TODO: Remove
      - id: set-test-type-for-float32
        run: |
          if [[ $GOOGLE_CLOUD_ENDPOINT == 'staging-wrenchworks.sandbox.googleapis.com' ]]; then
            echo "FLOAT32_TEST_TYPE=float4" >> $GITHUB_ENV
          else
            echo "FLOAT32_TEST_TYPE=float8" >> $GITHUB_ENV
          fi
      - id: set-excluded-integration-tests
        if: github.event_name == 'pull_request'
        run: |
          echo "EXCLUDED_INTEGRATION_TESTS=SlowTest" >> $GITHUB_ENV
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: zulu
          java-version: 21
      - run: java -version
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.26.x'
      - run: go version
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.14'
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '4.0.6'
          bundler-cache: true
      - name: Setup psql
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client-18
      - name: Create PostgreSQL test database
        run: |
          psql -h /pg -U postgres -c "CREATE DATABASE pgadapter"
      - name: Run unit tests
        run: mvn test -B -Ptest-all -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        env:
          POSTGRES_HOST: /pg
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_DATABASE: pgadapter
      - name: Run unit tests with virtual threads
        run: mvn test -Dpgadapter.use_virtual_threads=true -Dpgadapter.use_virtual_grpc_transport_threads=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -Ptest-all
        env:
          POSTGRES_HOST: /pg
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_DATABASE: pgadapter
      - name: Auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          credentials_json: ${{ secrets.JSON_SERVICE_ACCOUNT_CREDENTIALS }}
      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Run integration tests
        run: mvn verify -B -Dclirr.skip=true -DskipITs=false -DskipUnits=true -Dpgadapter.test_float4_type="$FLOAT32_TEST_TYPE" -DexcludedIntegrationTests="$EXCLUDED_INTEGRATION_TESTS" -DPG_ADAPTER_HOST="https://$GOOGLE_CLOUD_ENDPOINT" -DPG_ADAPTER_INSTANCE="$GOOGLE_CLOUD_INSTANCE" -DPG_ADAPTER_DATABASE="$GOOGLE_CLOUD_DATABASE"
        env:
          POSTGRES_HOST: /pg
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_DATABASE: pgadapter
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          directory: ./target/site/jacoco-merged-test-coverage-report
          fail_ci_if_error: false
          flags: all_tests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
      - id: create-issue-on-failure
        if: "${{ failure() && (github.event.schedule=='52 4 * * *' || github.event.schedule=='14 3 * * *' || inputs.endpoint != '')}}"
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENDPOINT: ${{ env.GOOGLE_CLOUD_ENDPOINT }}
        with:
          filename: .github/integration-test-failed-template.md
          assignees: olavloite, rayudu3745
