on:
  # This allows manual activation of this action for testing.
  workflow_dispatch:
  pull_request:
    branches: [ postgresql-dialect ]
name: integration-tests-against-docker
jobs:
  integration_tests:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLOUD_INSTANCE: "pgadapter-testing"
      GOOGLE_CLOUD_ENDPOINT: "spanner.googleapis.com"
      DOCKERFILE: "build/Dockerfile.ci"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.JSON_SERVICE_ACCOUNT_CREDENTIALS }}'
      - run: mvn verify -Dclirr.skip=true -DskipITs=false -DPG_ADAPTER_HOST="https://${GOOGLE_CLOUD_ENDPOINT}" -DPG_ADAPTER_INSTANCE="${GOOGLE_CLOUD_INSTANCE}" -DPG_ADAPTER_DATABASE="${GOOGLE_CLOUD_DATABASE}"
