on:
  push:
    branches:
      - postgresql-dialect
  pull_request:
  workflow_dispatch:
name: samples
jobs:
  java-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Run JDBC Sample tests
        working-directory: ./samples/java/jdbc
        run: mvn test -B
      - name: Run Hibernate Sample tests
        working-directory: ./samples/java/hibernate
        run: mvn test -B
