on:
  pull_request:
name: units
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{matrix.java}}
      - run: java -version
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20.7'
      - run: go version
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: python --version
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - run: mvn -B test -Ptest-all -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  windows:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{matrix.java}}
      - run: java -version
      - run: mvn -B test
  macos:
    runs-on: macos-latest
    env:
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{matrix.java}}
      - run: java -version
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20.7'
      - run: go version
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: python --version
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - run: mvn -B test -Ptest-all -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  ubuntu-jdk21:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [21]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{matrix.java}}
      - run: java -version
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.7'
      - run: go version
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: python --version
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - run: mvn -B test -Pjdk21 -Ptest-all -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
