on:
  pull_request:
name: units
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{matrix.java}}
      - run: java -version
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.7'
      - run: go version
      - run: mvn -B test -Ptest-all
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./target/site/jacoco
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
  windows:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{matrix.java}}
      - run: java -version
      - run: mvn -B test
